Add support for custom weight decay optimizer
EmbarkStudios/emote pull request #129
Opened 2023-05-19 13:39 UTC by spetravic

Creates a modified AdamW (that inherits from the standard AdamW) as suggested in _[Efficient deep reinforcement learning requires regulating overfitting](https://arxiv.org/pdf/2304.10466.pdf)_.

ModifiedAdamW disables weight decay for the bias, additional modules (such as LayerNorm), and specific named layers (e.g. the paper suggests excluding the final layer in the Q networks, which can be done by passing `layers_to_exclude = ["final_layer"]`). 

The function for separating the modules was adapted from a [PyTorch minGPT implementation](https://github.com/karpathy/minGPT/blob/3ed14b2cec0dfdad3f4b2831f2b4a86d11aef150/mingpt/model.py#L136) that is MIT licensed.

2023-05-19 14:49 UTC, tgolsson requested changes
Looks very nice! Super clean, with some nitpicks here and there!

2023-05-19 14:49 UTC, tgolsson commented on emote/optimizers.py
> +    layers_to_exclude: Optional[List[str]] = None,
If you add `from __future__ import annotations` you can write this as:
```suggestion
    whitelist_weight_modules: tuple[torch.nn.Module, ...],
    blacklist_weight_modules: tuple[torch.nn.Module, ...],
    layers_to_exclude: set[str] | None = None,
```

which is a bit more modern!

2023-05-19 14:49 UTC, tgolsson commented on emote/optimizers.py
> +            fpn = "%s.%s" % (mn, pn) if mn else pn
Do you have to pay per letter? :D

2023-05-19 14:49 UTC, tgolsson commented on emote/optimizers.py
> +            elif pn.endswith("weight") and isinstance(m, whitelist_weight_modules):
I don't understand the usage of `isinstance` here! Either the type annotation lies or the code is wrong. You're taking a list of objects, but you're checking if m is a type. Should `whitelist_weight_modules` be `tuple[Type[nn.Module]]`?

2023-05-19 14:49 UTC, tgolsson commented on emote/optimizers.py
> +                "params": [param_dict[pn] for pn in sorted(list(no_decay))],
Is the order important here? It seems to me it wouldn't matter... :-) 

Also, if we need them to be lists here, why not make them lists and sort in the helper function?

2023-05-19 14:49 UTC, tgolsson commented on tests/test_modified_adamw.py
> +        whitelist_weight_modules=(torch.nn.Linear),
probably missing commas here as well

2023-05-19 14:49 UTC, tgolsson commented on tests/test_modified_adamw.py
> +    ), f"There should be one group that has weight decay, but there are {no_wd}"
Very nice tests! Could you reverse some of these tests and also pass in *bad* data and ensure it fails? There's the pattern

```python
a = {}
with pytest.raises(KeyError):
     a['foo'] # exception gets caught and test passes, but fails the test if the exception isn't caught 
```
You can also ensure the message is what you want using regex, like this:

```python
with pytest.raises(
    ValueError,
    match=r"My custom message: '[a-z]+'"
):
    raise ValueError("My custom message: 'foobar'")    
```

2023-05-21 22:43 UTC, tgolsson commented on emote/optimizers.py
> +            fpn = "%s.%s" % (mn, pn) if mn else pn
Also use f-strings!

2023-05-22 10:44 UTC, singhblom approved these changes
@tgolsson gave good feedback which I agree with, but apart from that it looks super nice. Looking forward to seeing the results of this. 👍🏼

2023-05-23 07:48 UTC, spetravic commented on emote/optimizers.py
> +        param_dict = {pn: p for pn, p in network.named_parameters()}
`network.named_parameters()` returns a generator, so the optimizer groups would have to be created in a different way. Converting to a dict and using the way it's written now seems cleaner to me than iterating through the modules with `next()` , but I could change it to use the generator instead if that is the preference.

2023-05-23 08:15 UTC, spetravic commented on emote/optimizers.py
> +        param_dict = {pn: p for pn, p in network.named_parameters()}
Yes, that works :)

2023-05-25 06:52 UTC, merged