Add more logging to ckpt/onnx/memory
EmbarkStudios/emote pull request #136
Opened 2023-05-30 08:49 UTC by jaxs-ribs

2023-05-30 09:00 UTC, tgolsson commented on emote/callbacks/checkpointing.py
> +        logging.info(f"Loading checkpoints from {final_path}")
Print before loading the file; then finished. (So like everywhere else :D)

2023-05-31 06:44 UTC, singhblom approved these changes

2023-06-01 09:56 UTC, tgolsson requested changes

2023-06-01 09:56 UTC, tgolsson commented on emote/memory/memory.py
> +        start_time = time.time()
This should be in the if at the bottom.

2023-06-01 11:43 UTC, tgolsson approved these changes

2023-06-01 11:54 UTC, merged